server:
  port: 8070
  forward-headers-strategy: framework
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auto-sharing-db
    username: postgres
    password: pass
  jpa:
    driverClassName: org.postgresql.Driver
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

app:
  auth:
    secret: 703373367639792442264529482B4D6251655468576D5A7134743777217A2543
    lifeTime: 1200_000  # 20 minute